// ─── Monaco Theme Definitions ────────────────────────────────────────────────
// Defines all application themes for Monaco Editor instances.
// Each theme maps to the corresponding CSS theme class in app.css.

import type * as Monaco from 'monaco-editor';

type MonacoInstance = typeof Monaco;

interface ThemeDef {
  base: 'vs' | 'vs-dark';
  rules: Monaco.editor.ITokenThemeRule[];
  colors: Record<string, string>;
}

const THEMES: Record<string, ThemeDef> = {
  'hyscode-dark': {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '6a737d', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c084fc' },
      { token: 'keyword.control', foreground: 'c084fc' },
      { token: 'string', foreground: '86efac' },
      { token: 'number', foreground: 'fbbf24' },
      { token: 'type', foreground: '60a5fa' },
      { token: 'type.identifier', foreground: '60a5fa' },
      { token: 'function', foreground: 'f0abfc' },
      { token: 'variable', foreground: 'e8e8e8' },
      { token: 'operator', foreground: 'e8e8e8' },
      { token: 'delimiter', foreground: '888888' },
      { token: 'tag', foreground: 'c084fc' },
      { token: 'attribute.name', foreground: '60a5fa' },
      { token: 'attribute.value', foreground: '86efac' },
      { token: 'regexp', foreground: 'fbbf24' },
    ],
    colors: {
      'editor.background': '#1a1a1a',
      'editor.foreground': '#f0f0f0',
      'editorLineNumber.foreground': '#4a4a4a',
      'editorLineNumber.activeForeground': '#b0b0b0',
      'editor.selectionBackground': '#a855f733',
      'editor.lineHighlightBackground': '#ffffff08',
      'editorCursor.foreground': '#a855f7',
      'editorIndentGuide.background': '#2a2a2a',
      'editorIndentGuide.activeBackground': '#3a3a3a',
      'editorBracketMatch.background': '#a855f722',
      'editorBracketMatch.border': '#a855f744',
      'editor.wordHighlightBackground': '#a855f718',
      'editorWidget.background': '#222222',
      'editorWidget.border': '#a855f738',
      'input.background': '#1a1a1a',
      'input.foreground': '#f0f0f0',
      'input.border': '#a855f738',
      'minimap.background': '#141414',
      'minimap.selectionHighlight': '#a855f755',
      'minimapGutter.addedBackground': '#3fb950',
      'minimapGutter.modifiedBackground': '#e3b341',
      'minimapGutter.deletedBackground': '#f85149',
      'editorOverviewRuler.addedForeground': '#3fb95088',
      'editorOverviewRuler.modifiedForeground': '#e3b34188',
      'editorOverviewRuler.deletedForeground': '#f8514988',
      'scrollbarSlider.background': '#a855f722',
      'scrollbarSlider.hoverBackground': '#a855f744',
      'scrollbarSlider.activeBackground': '#a855f766',
    },
  },

  'hyscode-light': {
    base: 'vs',
    rules: [
      { token: 'comment', foreground: '6b7280', fontStyle: 'italic' },
      { token: 'keyword', foreground: '7c3aed' },
      { token: 'keyword.control', foreground: '7c3aed' },
      { token: 'string', foreground: '16a34a' },
      { token: 'number', foreground: 'd97706' },
      { token: 'type', foreground: '1d4ed8' },
      { token: 'type.identifier', foreground: '1d4ed8' },
      { token: 'function', foreground: '9333ea' },
      { token: 'variable', foreground: '1a1a1a' },
      { token: 'operator', foreground: '374151' },
      { token: 'delimiter', foreground: '6b7280' },
      { token: 'tag', foreground: '7c3aed' },
      { token: 'attribute.name', foreground: '1d4ed8' },
      { token: 'attribute.value', foreground: '16a34a' },
      { token: 'regexp', foreground: 'd97706' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#1a1a1a',
      'editorLineNumber.foreground': '#c0c0c0',
      'editorLineNumber.activeForeground': '#666666',
      'editor.selectionBackground': '#7c3aed22',
      'editor.lineHighlightBackground': '#f5f5f5',
      'editorCursor.foreground': '#7c3aed',
      'editorIndentGuide.background': '#e8e8e8',
      'editorIndentGuide.activeBackground': '#d0d0d0',
      'editorBracketMatch.background': '#7c3aed22',
      'editorBracketMatch.border': '#7c3aed44',
      'editor.wordHighlightBackground': '#7c3aed18',
      'editorWidget.background': '#f5f5f5',
      'editorWidget.border': '#e0e0e0',
      'input.background': '#ffffff',
      'input.foreground': '#1a1a1a',
      'input.border': '#e0e0e0',
      'minimap.background': '#fafafa',
      'minimap.selectionHighlight': '#7c3aed44',
      'minimapGutter.addedBackground': '#22c55e',
      'minimapGutter.modifiedBackground': '#eab308',
      'minimapGutter.deletedBackground': '#ef4444',
      'editorOverviewRuler.addedForeground': '#22c55e88',
      'editorOverviewRuler.modifiedForeground': '#eab30888',
      'editorOverviewRuler.deletedForeground': '#ef444488',
      'scrollbarSlider.background': '#7c3aed18',
      'scrollbarSlider.hoverBackground': '#7c3aed30',
      'scrollbarSlider.activeBackground': '#7c3aed48',
    },
  },

  'hyscode-nord': {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '636e82', fontStyle: 'italic' },
      { token: 'keyword', foreground: '81a1c1' },
      { token: 'keyword.control', foreground: '81a1c1' },
      { token: 'string', foreground: 'a3be8c' },
      { token: 'number', foreground: 'b48ead' },
      { token: 'type', foreground: '88c0d0' },
      { token: 'type.identifier', foreground: '8fbcbb' },
      { token: 'function', foreground: '88c0d0' },
      { token: 'variable', foreground: 'd8dee9' },
      { token: 'operator', foreground: '81a1c1' },
      { token: 'delimiter', foreground: 'a0a8b7' },
      { token: 'tag', foreground: '81a1c1' },
      { token: 'attribute.name', foreground: '8fbcbb' },
      { token: 'attribute.value', foreground: 'a3be8c' },
      { token: 'regexp', foreground: 'ebcb8b' },
    ],
    colors: {
      'editor.background': '#2e3440',
      'editor.foreground': '#d8dee9',
      'editorLineNumber.foreground': '#4c566a',
      'editorLineNumber.activeForeground': '#d8dee9',
      'editor.selectionBackground': '#88c0d033',
      'editor.lineHighlightBackground': '#3b425208',
      'editorCursor.foreground': '#88c0d0',
      'editorIndentGuide.background': '#3b4252',
      'editorIndentGuide.activeBackground': '#4c566a',
      'editorBracketMatch.background': '#88c0d022',
      'editorBracketMatch.border': '#88c0d044',
      'editor.wordHighlightBackground': '#88c0d018',
      'editorWidget.background': '#3b4252',
      'editorWidget.border': '#4c566a',
      'input.background': '#3b4252',
      'input.foreground': '#d8dee9',
      'input.border': '#4c566a',
      'minimap.background': '#292e39',
      'minimap.selectionHighlight': '#88c0d044',
      'minimapGutter.addedBackground': '#a3be8c',
      'minimapGutter.modifiedBackground': '#ebcb8b',
      'minimapGutter.deletedBackground': '#bf616a',
      'editorOverviewRuler.addedForeground': '#a3be8c88',
      'editorOverviewRuler.modifiedForeground': '#ebcb8b88',
      'editorOverviewRuler.deletedForeground': '#bf616a88',
      'scrollbarSlider.background': '#4c566a55',
      'scrollbarSlider.hoverBackground': '#4c566a88',
      'scrollbarSlider.activeBackground': '#4c566aaa',
    },
  },

  'hyscode-monokai': {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '75715e', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'f92672' },
      { token: 'keyword.control', foreground: 'f92672' },
      { token: 'string', foreground: 'e6db74' },
      { token: 'number', foreground: 'ae81ff' },
      { token: 'type', foreground: '66d9ef', fontStyle: 'italic' },
      { token: 'type.identifier', foreground: 'a6e22e' },
      { token: 'function', foreground: 'a6e22e' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'operator', foreground: 'f92672' },
      { token: 'delimiter', foreground: '8f908a' },
      { token: 'tag', foreground: 'f92672' },
      { token: 'attribute.name', foreground: 'a6e22e' },
      { token: 'attribute.value', foreground: 'e6db74' },
      { token: 'regexp', foreground: 'e6db74' },
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#f8f8f2',
      'editorLineNumber.foreground': '#4e4f47',
      'editorLineNumber.activeForeground': '#8f908a',
      'editor.selectionBackground': '#f9267233',
      'editor.lineHighlightBackground': '#2d2e2708',
      'editorCursor.foreground': '#f8f8f0',
      'editorIndentGuide.background': '#3e3d32',
      'editorIndentGuide.activeBackground': '#4e4d42',
      'editorBracketMatch.background': '#f9267222',
      'editorBracketMatch.border': '#f9267244',
      'editor.wordHighlightBackground': '#f9267218',
      'editorWidget.background': '#2d2e27',
      'editorWidget.border': '#3e3d32',
      'input.background': '#2d2e27',
      'input.foreground': '#f8f8f2',
      'input.border': '#3e3d32',
      'minimap.background': '#1e1f1c',
      'minimap.selectionHighlight': '#f9267244',
      'minimapGutter.addedBackground': '#a6e22e',
      'minimapGutter.modifiedBackground': '#e6db74',
      'minimapGutter.deletedBackground': '#f92672',
      'editorOverviewRuler.addedForeground': '#a6e22e88',
      'editorOverviewRuler.modifiedForeground': '#e6db7488',
      'editorOverviewRuler.deletedForeground': '#f9267288',
      'scrollbarSlider.background': '#4e4d4255',
      'scrollbarSlider.hoverBackground': '#4e4d4288',
      'scrollbarSlider.activeBackground': '#4e4d42aa',
    },
  },

  'hyscode-dracula': {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff79c6' },
      { token: 'keyword.control', foreground: 'ff79c6' },
      { token: 'string', foreground: 'f1fa8c' },
      { token: 'number', foreground: 'bd93f9' },
      { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
      { token: 'type.identifier', foreground: '8be9fd' },
      { token: 'function', foreground: '50fa7b' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'operator', foreground: 'ff79c6' },
      { token: 'delimiter', foreground: 'a0a4b8' },
      { token: 'tag', foreground: 'ff79c6' },
      { token: 'attribute.name', foreground: '50fa7b' },
      { token: 'attribute.value', foreground: 'f1fa8c' },
      { token: 'regexp', foreground: 'f1fa8c' },
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editorLineNumber.foreground': '#44475a',
      'editorLineNumber.activeForeground': '#a0a4b8',
      'editor.selectionBackground': '#bd93f933',
      'editor.lineHighlightBackground': '#2d2f3d08',
      'editorCursor.foreground': '#f8f8f2',
      'editorIndentGuide.background': '#3a3c4e',
      'editorIndentGuide.activeBackground': '#44475a',
      'editorBracketMatch.background': '#bd93f922',
      'editorBracketMatch.border': '#bd93f944',
      'editor.wordHighlightBackground': '#bd93f918',
      'editorWidget.background': '#2d2f3d',
      'editorWidget.border': '#44475a',
      'input.background': '#2d2f3d',
      'input.foreground': '#f8f8f2',
      'input.border': '#44475a',
      'minimap.background': '#21222c',
      'minimap.selectionHighlight': '#bd93f944',
      'minimapGutter.addedBackground': '#50fa7b',
      'minimapGutter.modifiedBackground': '#f1fa8c',
      'minimapGutter.deletedBackground': '#ff5555',
      'editorOverviewRuler.addedForeground': '#50fa7b88',
      'editorOverviewRuler.modifiedForeground': '#f1fa8c88',
      'editorOverviewRuler.deletedForeground': '#ff555588',
      'scrollbarSlider.background': '#44475a55',
      'scrollbarSlider.hoverBackground': '#44475a88',
      'scrollbarSlider.activeBackground': '#44475aaa',
    },
  },

  'hyscode-github-dark': {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '8b949e', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff7b72' },
      { token: 'keyword.control', foreground: 'ff7b72' },
      { token: 'string', foreground: 'a5d6ff' },
      { token: 'number', foreground: '79c0ff' },
      { token: 'type', foreground: 'ffa657' },
      { token: 'type.identifier', foreground: 'ffa657' },
      { token: 'function', foreground: 'd2a8ff' },
      { token: 'variable', foreground: 'c9d1d9' },
      { token: 'operator', foreground: 'ff7b72' },
      { token: 'delimiter', foreground: '8b949e' },
      { token: 'tag', foreground: '7ee787' },
      { token: 'attribute.name', foreground: '79c0ff' },
      { token: 'attribute.value', foreground: 'a5d6ff' },
      { token: 'regexp', foreground: '7ee787' },
    ],
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#c9d1d9',
      'editorLineNumber.foreground': '#30363d',
      'editorLineNumber.activeForeground': '#8b949e',
      'editor.selectionBackground': '#58a6ff33',
      'editor.lineHighlightBackground': '#161b2208',
      'editorCursor.foreground': '#58a6ff',
      'editorIndentGuide.background': '#21262d',
      'editorIndentGuide.activeBackground': '#30363d',
      'editorBracketMatch.background': '#58a6ff22',
      'editorBracketMatch.border': '#58a6ff44',
      'editor.wordHighlightBackground': '#58a6ff18',
      'editorWidget.background': '#161b22',
      'editorWidget.border': '#30363d',
      'input.background': '#161b22',
      'input.foreground': '#c9d1d9',
      'input.border': '#30363d',
      'minimap.background': '#010409',
      'minimap.selectionHighlight': '#58a6ff44',
      'minimapGutter.addedBackground': '#3fb950',
      'minimapGutter.modifiedBackground': '#d29922',
      'minimapGutter.deletedBackground': '#f85149',
      'editorOverviewRuler.addedForeground': '#3fb95088',
      'editorOverviewRuler.modifiedForeground': '#d2992288',
      'editorOverviewRuler.deletedForeground': '#f8514988',
      'scrollbarSlider.background': '#30363d55',
      'scrollbarSlider.hoverBackground': '#30363d88',
      'scrollbarSlider.activeBackground': '#30363daa',
    },
  },
};

/** Maps a settings ThemeId to the corresponding Monaco theme name. */
export function getMonacoThemeName(themeId: string): string {
  switch (themeId) {
    case 'hyscode-dark':   return 'hyscode-dark';
    case 'hyscode-light':  return 'hyscode-light';
    case 'nord':           return 'hyscode-nord';
    case 'monokai':        return 'hyscode-monokai';
    case 'dracula':        return 'hyscode-dracula';
    case 'github-dark':    return 'hyscode-github-dark';
    default:               return 'hyscode-dark';
  }
}

/** Registers all HysCode themes in a Monaco instance. Call in beforeMount. */
export function defineAllMonacoThemes(monaco: MonacoInstance): void {
  for (const [name, def] of Object.entries(THEMES)) {
    monaco.editor.defineTheme(name, {
      base: def.base,
      inherit: true,
      rules: def.rules,
      colors: def.colors,
    });
  }
}
