// ─── Provider & Model Catalog ─────────────────────────────────────────────────
// Single source of truth for provider/model metadata used by both the AI
// settings tab and the agent-input model selector.
//
// Thinking-mode metadata mirrors the `thinkingVariants` field declared in
// `packages/ai-providers/src/types.ts` and the provider implementations
// (opencode-zen.ts, opencode-go.ts, etc.). The harness bridge falls back to
// the provider's `thinkingVariants` when this catalog does not have an entry
// for a custom user-added model.

import type { CustomModel } from '@/stores/settings-store';

export interface ModelInfo {
  id: string;
  name: string;
  /** Whether this model supports thinking/reasoning modes */
  supportsThinking?: boolean;
  /** Type of thinking control supported by this model */
  thinkingType?: 'anthropic' | 'openai' | 'gemini' | 'kimi' | 'deepseek' | 'mistral' | 'none';
  /** Available thinking levels for this model (if applicable) */
  thinkingLevels?: string[];
  /** Available reasoning modes (e.g. GPT-5.6 standard|pro) */
  thinkingModes?: string[];
}

export interface ProviderInfo {
  id: string;
  name: string;
  models: ModelInfo[];
  needsKey: boolean;
  supportsCustomModels?: boolean;
}

export const PROVIDERS: ProviderInfo[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    needsKey: true,
    models: [
      {
        id: 'claude-fable-5',
        name: 'Claude Fable 5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-5',
        name: 'Claude Opus 5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4-8',
        name: 'Claude Opus 4.8',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-sonnet-5',
        name: 'Claude Sonnet 5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4-7',
        name: 'Claude Opus 4.7',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4-6',
        name: 'Claude Opus 4.6',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'claude-opus-4-5',
        name: 'Claude Opus 4.5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'claude-sonnet-4-5',
        name: 'Claude Sonnet 4.5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'claude-haiku-4-5',
        name: 'Claude Haiku 4.5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    needsKey: true,
    models: [
      {
        id: 'gpt-5.6-sol',
        name: 'GPT-5.6 Sol',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'gpt-5.6-terra',
        name: 'GPT-5.6 Terra',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'gpt-5.6-luna',
        name: 'GPT-5.6 Luna',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'gpt-5.5',
        name: 'GPT-5.5',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.5-pro',
        name: 'GPT-5.5 Pro',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.4',
        name: 'GPT-5.4',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.4-pro',
        name: 'GPT-5.4 Pro',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.4-mini',
        name: 'GPT-5.4 Mini',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      { id: 'gpt-5.4-nano', name: 'GPT-5.4 Nano', supportsThinking: false, thinkingType: 'none' },
      {
        id: 'gpt-5.3-codex',
        name: 'GPT-5.3 Codex',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
    ],
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    needsKey: true,
    models: [
      {
        id: 'gemini-3.6-flash',
        name: 'Gemini 3.6 Flash',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gemini-3.5-flash',
        name: 'Gemini 3.5 Flash',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gemini-3.5-flash-lite',
        name: 'Gemini 3.5 Flash-Lite',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'gemini-3.1-pro',
        name: 'Gemini 3.1 Pro',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gemini-3-flash',
        name: 'Gemini 3 Flash',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    needsKey: true,
    supportsCustomModels: true,
    models: [
      {
        id: 'anthropic/claude-fable-5',
        name: 'Claude Fable 5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'anthropic/claude-opus-4-8',
        name: 'Claude Opus 4.8',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'anthropic/claude-sonnet-5',
        name: 'Claude Sonnet 5',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'anthropic/claude-opus-4-7',
        name: 'Claude Opus 4.7',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'anthropic/claude-opus-4-6',
        name: 'Claude Opus 4.6',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'anthropic/claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'openai/gpt-5.6-sol',
        name: 'GPT-5.6 Sol',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'openai/gpt-5.6-terra',
        name: 'GPT-5.6 Terra',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'openai/gpt-5.6-luna',
        name: 'GPT-5.6 Luna',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'openai/gpt-5.5',
        name: 'GPT-5.5',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'openai/gpt-5.4',
        name: 'GPT-5.4',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'openai/gpt-5.4-mini',
        name: 'GPT-5.4 Mini',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      {
        id: 'google/gemini-3.6-flash',
        name: 'Gemini 3.6 Flash',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'google/gemini-3.5-flash',
        name: 'Gemini 3.5 Flash',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'google/gemini-3.5-flash-lite',
        name: 'Gemini 3.5 Flash-Lite',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'google/gemini-3.1-pro',
        name: 'Gemini 3.1 Pro',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'google/gemini-3-flash',
        name: 'Gemini 3 Flash',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'x-ai/grok-4.5',
        name: 'Grok 4.5',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'x-ai/grok-build-0.1',
        name: 'Grok Build 0.1',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'deepseek/deepseek-v4-pro',
        name: 'DeepSeek V4 Pro',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'deepseek/deepseek-v4-flash',
        name: 'DeepSeek V4 Flash',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'qwen/qwen3.7-max',
        name: 'Qwen3.7 Max',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'qwen/qwen3.7-plus',
        name: 'Qwen3.7 Plus',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'moonshotai/kimi-k3',
        name: 'Kimi K3',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'max'],
      },
      {
        id: 'moonshotai/kimi-k2.7-code',
        name: 'Kimi K2.7 Code',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'moonshotai/kimi-k2.6',
        name: 'Kimi K2.6',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'z-ai/glm-5.2',
        name: 'GLM 5.2',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'z-ai/glm-5.1',
        name: 'GLM 5.1',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'minimax/minimax-m3',
        name: 'MiniMax M3',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['adaptive', 'disabled'],
      },
      {
        id: 'tencent/hy3',
        name: 'Hy3 (Tencent Hunyuan 3)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      {
        id: 'xiaomi/mimo-v2.5',
        name: 'MiMo V2.5',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'xiaomi/mimo-v2.5-pro',
        name: 'MiMo V2.5 Pro',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (local)',
    needsKey: false,
    supportsCustomModels: true,
    models: [
      { id: 'llama4', name: 'Llama 4', supportsThinking: false, thinkingType: 'none' },
      {
        id: 'qwen3',
        name: 'Qwen 3',
        supportsThinking: true,
        thinkingType: 'none',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'deepseek-r1',
        name: 'DeepSeek R1',
        supportsThinking: true,
        thinkingType: 'deepseek',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'deepseek-coder-v2',
        name: 'DeepSeek Coder V2',
        supportsThinking: false,
        thinkingType: 'none',
      },
    ],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    needsKey: false, // Uses OAuth, not API key
    models: [
      // 0× (free)
      {
        id: 'gpt-5-mini',
        name: 'GPT-5 Mini (Copilot)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'raptor-mini',
        name: 'Raptor Mini (Copilot)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'gpt-5.5',
        name: 'GPT-5.5 (Copilot)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      // 0.33×
      {
        id: 'claude-haiku-4.5',
        name: 'Claude Haiku 4.5 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'gemini-3-flash',
        name: 'Gemini 3 Flash (Copilot)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'gemini-3.5-flash',
        name: 'Gemini 3.5 Flash (Copilot)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'gemini-3.5-flash-lite',
        name: 'Gemini 3.5 Flash-Lite (Copilot)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'gemini-3.6-flash',
        name: 'Gemini 3.6 Flash (Copilot)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gpt-5.4-mini',
        name: 'GPT-5.4 Mini (Copilot)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      // 1×
      {
        id: 'claude-sonnet-4.5',
        name: 'Claude Sonnet 4.5 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'claude-sonnet-4.6',
        name: 'Claude Sonnet 4.6 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'gemini-3.1-pro',
        name: 'Gemini 3.1 Pro (Copilot)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gpt-5.3-codex',
        name: 'GPT-5.3-Codex (Copilot)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.4',
        name: 'GPT-5.4 (Copilot)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'mai-code-1-flash',
        name: 'MAI-Code-1-Flash (Copilot)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      // 3×
      {
        id: 'claude-opus-4.8',
        name: 'Claude Opus 4.8 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4.8-fast',
        name: 'Claude Opus 4.8 Fast (Copilot Preview)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-5',
        name: 'Claude Opus 5 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4.7',
        name: 'Claude Opus 4.7 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4.5',
        name: 'Claude Opus 4.5 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'claude-opus-4.6',
        name: 'Claude Opus 4.6 (Copilot)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
    ],
  },
  {
    id: 'opencode-zen',
    name: 'OpenCode Zen',
    needsKey: true,
    models: [
      {
        id: 'gpt-5.6-sol',
        name: 'GPT 5.6 Sol (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'gpt-5.6-terra',
        name: 'GPT 5.6 Terra (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'gpt-5.6-luna',
        name: 'GPT 5.6 Luna (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'gpt-5.5',
        name: 'GPT 5.5 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.5-pro',
        name: 'GPT 5.5 Pro (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.4',
        name: 'GPT 5.4 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.4-pro',
        name: 'GPT 5.4 Pro (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.4-mini',
        name: 'GPT 5.4 Mini (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      {
        id: 'gpt-5.4-nano',
        name: 'GPT 5.4 Nano (Zen)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'gpt-5.3-codex',
        name: 'GPT 5.3 Codex (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.3-codex-spark',
        name: 'GPT 5.3 Codex Spark (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      {
        id: 'gpt-5.2',
        name: 'GPT 5.2 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.2-codex',
        name: 'GPT 5.2 Codex (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.1',
        name: 'GPT 5.1 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.1-codex',
        name: 'GPT 5.1 Codex (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.1-codex-max',
        name: 'GPT 5.1 Codex Max (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.1-codex-mini',
        name: 'GPT 5.1 Codex Mini (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium'],
      },
      {
        id: 'gpt-5',
        name: 'GPT 5 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5-codex',
        name: 'GPT 5 Codex (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      { id: 'gpt-5-nano', name: 'GPT 5 Nano (Zen)', supportsThinking: false, thinkingType: 'none' },
      {
        id: 'gemini-3.7-flash',
        name: 'Gemini 3.7 Flash (Zen)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gemini-3.6-flash',
        name: 'Gemini 3.6 Flash (Zen)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gemini-3.5-flash',
        name: 'Gemini 3.5 Flash (Zen)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gemini-3.5-flash-lite',
        name: 'Gemini 3.5 Flash-Lite (Zen)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'gemini-3.1-pro',
        name: 'Gemini 3.1 Pro (Zen)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'gemini-3-flash',
        name: 'Gemini 3 Flash (Zen)',
        supportsThinking: true,
        thinkingType: 'gemini',
        thinkingLevels: ['low', 'medium'],
      },
      {
        id: 'claude-fable-5',
        name: 'Claude Fable 5 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-5',
        name: 'Claude Opus 5 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4-8',
        name: 'Claude Opus 4.8 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4-7',
        name: 'Claude Opus 4.7 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-opus-4-6',
        name: 'Claude Opus 4.6 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'claude-opus-4-5',
        name: 'Claude Opus 4.5 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'claude-sonnet-5',
        name: 'Claude Sonnet 5 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'claude-sonnet-4-5',
        name: 'Claude Sonnet 4.5 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'claude-haiku-4-5',
        name: 'Claude Haiku 4.5 (Zen)',
        supportsThinking: true,
        thinkingType: 'anthropic',
        thinkingLevels: ['low', 'medium', 'high', 'max'],
      },
      {
        id: 'qwen3.7-max',
        name: 'Qwen3.7 Max (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'qwen3.7-plus',
        name: 'Qwen3.7 Plus (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'qwen3.6-plus',
        name: 'Qwen3.6 Plus (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'qwen3.5-plus',
        name: 'Qwen3.5 Plus (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'minimax-m3',
        name: 'MiniMax M3 (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['adaptive', 'disabled'],
      },
      {
        id: 'minimax-m2.7',
        name: 'MiniMax M2.7 (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'minimax-m2.5',
        name: 'MiniMax M2.5 (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'glm-5.2',
        name: 'GLM 5.2 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'glm-5.1',
        name: 'GLM 5.1 (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'glm-5',
        name: 'GLM 5 (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'kimi-k3',
        name: 'Kimi K3 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'max'],
      },
      {
        id: 'kimi-k2.7-code',
        name: 'Kimi K2.7 Code (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'kimi-k2.6',
        name: 'Kimi K2.6 (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'kimi-k2.5',
        name: 'Kimi K2.5 (Zen)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'deepseek-v4-pro',
        name: 'DeepSeek V4 Pro (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'deepseek-v4-flash',
        name: 'DeepSeek V4 Flash (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'grok-4.6',
        name: 'Grok 4.6 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'grok-4.5',
        name: 'Grok 4.5 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'grok-build-0.1',
        name: 'Grok Build 0.1 (Zen)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'muse-spark-1.2',
        name: 'Muse Spark 1.2 (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'minimal', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'big-pickle',
        name: 'Big Pickle (Zen)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'mimo-v2.5-free',
        name: 'MiMo V2.5 Free (Zen)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'laguna-s-2.1-free',
        name: 'Laguna S 2.1 Free (Zen)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'nemotron-3-ultra-free',
        name: 'Nemotron 3 Ultra Free (Zen)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'deepseek-v4-flash-free',
        name: 'DeepSeek V4 Flash Free (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'x-preview-f-free',
        name: 'Ox Alpha Free (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'low', 'high', 'max'],
      },
      {
        id: 'hy3-free',
        name: 'Hy3 Free (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      {
        id: 'nemotron-3.5-lightning-free',
        name: 'Nemotron 3.5 Lightning Free (Zen)',
        supportsThinking: false,
        thinkingType: 'none',
      },
      {
        id: 'muse-spark-1.2-contributor-free',
        name: 'Muse Spark 1.2 Contributor Free (Zen)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'minimal', 'low', 'medium', 'high', 'xhigh'],
      },
    ],
  },
  {
    id: 'opencode-go',
    name: 'OpenCode Go',
    needsKey: true,
    models: [
      {
        id: 'grok-4.5',
        name: 'Grok 4.5 (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'grok-4.6',
        name: 'Grok 4.6 (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['low', 'medium', 'high'],
      },
      {
        id: 'glm-5.3',
        name: 'GLM 5.3 (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'glm-5.2',
        name: 'GLM 5.2 (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'glm-5.1',
        name: 'GLM 5.1 (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'kimi-k3',
        name: 'Kimi K3 (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'max'],
      },
      {
        id: 'kimi-k2.7-code',
        name: 'Kimi K2.7 Code (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'kimi-k2.6',
        name: 'Kimi K2.6 (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'longcat-2.0',
        name: 'LongCat 2.0 (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'mimo-v2.5',
        name: 'MiMo V2.5 (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'mimo-v2.5-pro',
        name: 'MiMo V2.5 Pro (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled', 'disabled'],
      },
      {
        id: 'deepseek-v4-pro',
        name: 'DeepSeek V4 Pro (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'deepseek-v4-flash',
        name: 'DeepSeek V4 Flash (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'deepseek-v4-flash-vision-exp',
        name: 'DeepSeek V4 Flash Vision Exp (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['high', 'max'],
      },
      {
        id: 'hy3',
        name: 'Hy3 (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high'],
      },
      {
        id: 'ox-alpha-free',
        name: 'Ox Alpha Free (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'low', 'high', 'max'],
      },
      {
        id: 'gpt-5.6-luna',
        name: 'GPT 5.6 Luna (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
        thinkingModes: ['standard', 'pro'],
      },
      {
        id: 'muse-spark-1.2-contributor',
        name: 'Muse Spark 1.2 Contributor (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'minimal', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'minimax-m3',
        name: 'MiniMax M3 (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['adaptive', 'disabled'],
      },
      {
        id: 'minimax-m2.7',
        name: 'MiniMax M2.7 (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'minimax-m2.5',
        name: 'MiniMax M2.5 (Go)',
        supportsThinking: true,
        thinkingType: 'kimi',
        thinkingLevels: ['enabled'],
      },
      {
        id: 'qwen3.8-max',
        name: 'Qwen3.8 Max (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'qwen3.7-max',
        name: 'Qwen3.7 Max (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'qwen3.7-plus',
        name: 'Qwen3.7 Plus (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
      {
        id: 'qwen3.6-plus',
        name: 'Qwen3.6 Plus (Go)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['default', 'high', 'max'],
      },
    ],
  },
  {
    id: 'codex',
    name: 'Codex (Agent)',
    needsKey: true,
    models: [
      {
        id: 'gpt-5.6-sol',
        name: 'GPT 5.6 Sol (Codex)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.6-terra',
        name: 'GPT 5.6 Terra (Codex)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.6-luna',
        name: 'GPT 5.6 Luna (Codex)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['minimal', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        id: 'gpt-5.5',
        name: 'GPT 5.5 (Codex)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.4',
        name: 'GPT 5.4 (Codex)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        id: 'gpt-5.4-mini',
        name: 'GPT 5.4 Mini (Codex)',
        supportsThinking: true,
        thinkingType: 'openai',
        thinkingLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
      },
    ],
  },
];

/** Get all models for a provider (catalog + user custom) */
export function getProviderModels(provider: ProviderInfo, customModels: CustomModel[]): ModelInfo[] {
  const customs = customModels.filter((c) => c.providerId === provider.id).map((c) => ({ id: c.modelId, name: c.name }));
  return [...provider.models, ...customs];
}

/** Check if a model is enabled for a provider.
 *  Absent key = all catalog models enabled by default. */
export function isModelEnabled(enabledModels: Record<string, string[]>, providerId: string, modelId: string): boolean {
  const explicit = enabledModels[providerId];
  if (!explicit) return true;
  return explicit.includes(modelId);
}

/** Get flat list of enabled models for a single provider */
export function getEnabledModelsForProvider(providerId: string, enabledModels: Record<string, string[]>, customModels: CustomModel[]): ModelInfo[] {
  const provider = PROVIDERS.find((p) => p.id === providerId);
  if (!provider) return [];
  const all = getProviderModels(provider, customModels);
  return all.filter((m) => isModelEnabled(enabledModels, providerId, m.id));
}

/** Get all enabled models grouped by provider */
export function getAllEnabledModelsGrouped(enabledModels: Record<string, string[]>, customModels: CustomModel[]): Array<{ provider: ProviderInfo; models: ModelInfo[] }> {
  return PROVIDERS.map((p) => ({
    provider: p,
    models: getEnabledModelsForProvider(p.id, enabledModels, customModels),
  })).filter((g) => g.models.length > 0);
}
